### ISSUE TITLE
[Android Pre-work]

### ISSUE THREAD

**Issue by nongdenchet** [nongdenchet/DO.IT#1]
I have completed pre-word app, please review it.
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Android submission, nongdenchet!

:frowning: Unfortunately **there are some problems** with your submission:
- I couldn't find how much time you spent on the assignment. Please include the number of hours spent on your assignment in your `README.md`.

**Comment by nongdenchet** [comment]
Sorry for the inconvenience, I have updated the number of hours
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Android submission, nongdenchet!

 :ice_cream: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by hoanle** [comment]
hi @nongdenchet 

Thanks for your submission

By far, this is the most complete & interesting submission we've got so far. You have done a wonderful job. 
- The UI is beautiful, effect are well-done.
- You have used recent dominant trends in Android development such as: Dependency Injection (Dagger 2), data-binding, rxandroid. My most favourite part is the Testing you implemented. There are not many Android developers (and companies in VN) doing such things in real project. 
- Your code style is very well-manage. The abstract level of classes is high. Easy to catch up and maintain

Honestly, i'm sure you have a solid knowledge on Android development. That puts me to the question that why you want to attend this class why you can even be a TA to other fresh-android-developers.

**Comment by nongdenchet** [comment]
Hi @hoanle I want to open my network between developers, I thought that your class is for talented developers. I am learning Rails (newbie) the last time I submit for ruby on rails but I didn't pass. I hope to work with you guys (I think your team is awesome). I think I could start with Android then Rails later, so this time I apply for Android. Thank you for your code review, I really care about code quality

**Comment by hoanle** [comment]
@nongdenchet 
We have an idea. How about you use your old submission on Rails class last time, add some optional features and resubmit for this coming class (next week). It's better to study something new instead of wasting time on something you have already mastered

**Comment by nongdenchet** [comment]
@hoanle Last time I have applied for Ruby on Rails, but I have not received any exercises or email for that class... I thought that my profile for ruby is not interesting enough

**Comment by hoanle** [comment]
@nongdenchet 

We will send a pre-work for this coming Rails class to your email. Please do it & submit this time (quickly i guess). I'm sure you can do it :)

**Comment by nongdenchet** [comment]
@hoanle thank you for your help. I will try my best, not so good at html/css :((

**Comment by nongdenchet** [comment]
@hoanle have you sent me the pre-work???

**Comment by harley** [comment]
hi @nongdenchet, can you apply for the Rails class via this link? http://apply.coderschool.vn/cohorts/ruby2-feb16/application/ -- I look forward to reviewing your applications. If you have any trouble at all, feel free to email ruby at coderschool dot vn and we'll respond quickly. Feel free to also add me on FB and message me.

**Comment by nongdenchet** [comment]
@harley I have received your email and link to the pre-work. But I can not access your link at http://apply.coderschool.vn/cohorts/ruby2-feb16/application/ (I got Not found page)

**Comment by nongdenchet** [comment]
close

**Comment by nongdenchet** [comment]
close #1

**Comment by nongdenchet** [comment]
closes #1

**Comment by harley** [comment]
sorry @nongdenchet -- that's the wrong link. this is the correct one :) http://apply.coderschool.vn/cohorts/ruby2-feb16/versions/due-soon/
but if you just follow the prework link, that's OK too I'll update the system accordingly.

**Comment by nongdenchet** [comment]
@harley Have added you on facebook, can we chat there?

**Comment by nongdenchet** [comment]
@harley @hoanle I think that I could not complete the pre-work in time. Anyway, thank you for your support. Maybe the next time I will apply to your courses. Best wishes for your business. By the way, hope that some day I could be your TA because I really enjoy sharing, teaching and helping developers realize the benefit of testing and high quality code
